import 'package:flutter/animation.dart';

Color secondaryMediumGray = Color(0xff292B3E);
Color primaryBlue = Color(0xff246BFD);
Color systemGrey = Color(0xff8E8E93);
Color primaryPurple = Color(0xff9C67F9);
Color primaryPink = Color(0xffF79293);
Color primaryTosca = Color(0xff76BBAA);
Color secondaryLightPink = Color(0xffFEEBF5);
Color secondaryLightYellow = Color(0xffFFF6E4);
Color primaryYellow = Color(0xffFFBE3C);
Color secondaryLightBlue = Color(0xffE6EBF8);
Color secondaryLightTosca = Color(0xffDDEEEA);
Color greenAccent = Color(0xff00CC39);
Color red = Color(0xffFF4343);
Color baseColorWhite = Color(0xffFFFFFF);
Color primaryFillColor = Color(0xffE4E4E6);
Color secondaryFillColor = Color(0xffE9E9EB);
Color secondaryLabelColor = Color(0xff8A8A8E);
Color quarternaryLabelColor = Color(0xffF8F8F8);
